apiVersion: v1
kind: Service
metadata:
  name: {{ include "store.mariadbHost" . }}
  labels:
    {{- include "store.labels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
spec:
  type: ClusterIP
  selector:
    {{- include "store.selectorLabels" (dict "root" . "component" "mariadb") | nindent 4 }}
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
