apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-wordpress
  labels:
    {{- include "store.labels" . | nindent 4 }}
    app.kubernetes.io/component: wordpress
spec:
  type: ClusterIP
  selector:
    {{- include "store.selectorLabels" (dict "root" . "component" "wordpress") | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
